# Site settings
title: Satoshi to Bitcoin
email: 
description: A satoshi to Bitcoin (BTC) converter.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://satoshitobitcoin.co" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: kramdown

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]